import { createSlice } from "@reduxjs/toolkit";

import { SkuType } from "../../utils/types";

// Define the initial state interface
interface InitialState {
  skuList: SkuType[]; // Type for the sku list
}

// Initial state of the skuSlice
const initialState: InitialState = {
  skuList: [], // Initial value for the sku list
};

// Create a slice for sku-related state management
const skuSlice = createSlice({
  name: "skuSlice", // Name of the slice
  initialState, // Initial state
  reducers: {
    // Reducer to set the sku list
    setSkuList: (state: InitialState, { payload }) => ({ ...state, skuList: payload }), // Update skuList with the data payload
  },
});

// Export the reducer generated by createSlice
export default skuSlice.reducer;

// Export actions generated by createSlice
export const { setSkuList } = skuSlice.actions;
