# Generated by Django 5.0.6 on 2024-05-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=50)),
                ('presentation', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('countries', models.TextField()),
            ],
        ),
    ]
